{% set name = "empiricaldist" %}
{% set version = "0.6.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/empiricaldist-{{ version }}.tar.gz
  sha256: 36833cd458c9a551da04d69271ab764d8ed8ac3125fb1371ae6c0f9a931760f4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - matplotlib-base
    - numpy
    - pandas
    - scipy

test:
  imports:
    - empiricaldist
  commands:
    - pip check
    - python -m unittest empiricaldist.test_empiricaldist
  requires:
    - pip

about:
  home: https://github.com/AllenDowney/empiricaldist
  summary: Python library that represents empirical distributions.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AllenDowney
    - jdblischak
