{% set name = "empiricaldist" %}
{% set version = "0.7.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/empiricaldist-{{ version }}.tar.gz
  sha256: 60da9080d41ff8856093e3fea2e9dbfd7b4996dfb69846145d914b08de9ab396

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy
    - pandas
    - scipy

test:
  imports:
    - empiricaldist
  commands:
    - pip check
    - python -m unittest empiricaldist.test_empiricaldist
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/AllenDowney/empiricaldist
  summary: Python library that represents empirical distributions.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AllenDowney
    - jdblischak
